# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phalanxiddatamodel',
            name='phalanx_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='phalanxiddatamodel',
            name='phalanx_uid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
