# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 23:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0003_auto_20170922_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phalanxiddatamodel',
            name='phalanx_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Fa-fxX0-9\\s]+$', 'Invalid id. Only hex characters allowed', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='phalanxiddatamodel',
            name='phalanx_uid',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Fa-fxX0-9\\s]+$', 'Invalid id. Only hex characters allowed', 'invalid')]),
        ),
    ]
