# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0005_auto_20170923_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='phalanxiddatamodel',
            name='gpio_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phalanxiddatamodel',
            name='radio_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phalanxiddatamodel',
            name='receiver_rssi',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phalanxiddatamodel',
            name='sender_rssi',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phalanxiddatamodel',
            name='timestamp',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phalanxiddatamodel',
            name='uart_test',
            field=models.BooleanField(default=False),
        ),
    ]
