# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0006_auto_20171004_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phalanxiddatamodel',
            name='receiver_rssi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phalanxiddatamodel',
            name='sender_rssi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
