# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0009_auto_20171009_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phalanxiddatamodel',
            name='phalanx_id',
        ),
        migrations.RemoveField(
            model_name='phalanxiddatamodel',
            name='phalanx_uid',
        ),
    ]
