# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0010_auto_20171009_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='phalanxiddatamodel',
            name='phalanx_id',
            field=models.CharField(max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phalanxiddatamodel',
            name='phalanx_uid',
            field=models.CharField(max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
