# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0012_auto_20171010_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='phalanxiddatamodel',
            name='phalanx_ok',
            field=models.BooleanField(default=False),
        ),
    ]
